---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Delete IP Route"
    dellos9_config:
      lines:
         - no ip route 1.2.3.4 255.255.255.0 1.2.3.4
         - end
         
 #   register: show_ver
 
