---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Set Description Vlan"
    dellos9_config:
      lines:
         - interface vlan 999
         - description Prueba AWX
         - end
