---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Set Description Gigabit Ethernet"
    dellos9_config:
      lines:
         - interface gigabitenthernet x/x
         - set description XXXX
         - end
