---
- hosts: leaf6a
  connection: local
  gather_facts: no

  tasks:
  - name: "Switch Port Mode Access"
    dellos9_config:
      lines:
         - interface gigabitethernet x/x/x
         - switchport mode access
         - end
