---
- hosts: idf1_datos_sw2
  connection: local
  gather_facts: no

  tasks:
  - name: "Switch Port Mode Trunk"
    dellos6_config:
      lines:
         - interface gigabitethernet 1/0/3
         - switchport mode trunk
         - end
